apiVersion: v1
kind: Pod
metadata:
  name: vcuda
spec:
  restartPolicy: Never
  containers:
  - image: nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04
    name: nvidia
    command: ["/bin/sh", "-c"]
    args: ["for i in `seq 10`; do /usr/local/nvidia/bin/nvidia-smi && sleep 1; done"]
    resources:
      requests:
        tencent.com/vcuda-core: 50
        tencent.com/vcuda-memory: 30
      limits:
        tencent.com/vcuda-core: 50
        tencent.com/vcuda-memory: 30
