apiVersion: v1
kind: Pod
metadata:
  name: fft
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
    - image: localhost:5000/fft
      name: fft
      env:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      resources:
        requests:
          tencent.com/vcuda-core: 10
          tencent.com/vcuda-memory: 2
          cpu: "100m"
          memory: "100Mi"
        limits:
          tencent.com/vcuda-core: 10
          tencent.com/vcuda-memory: 2
          cpu: "100m"
          memory: "100Mi"
